### ISSUE TITLE
deluxetable crash if floating and final row lacking `\\`

### ISSUE THREAD

**Issue by pkgw** [AASJournals/AASTeX60#10] opened 2016-04-05 13:19 UTC
If you have a `deluxetable` in `floattable` mode, you get a crash if the final table row does not end with a `\\`. Standard LaTeX tables should not have a `\\` at the end of the final row so it's not crazy to think that this might happen. I mean, I ran into the issue. Sample:

```
\documentclass{aastex6}
\begin{document}
\title{Demo}
\author{Me}
\begin{abstract} Hello \end{abstract}

\floattable
\begin{deluxetable}{cc}
\tablecaption{Demo}
\tablehead{
\colhead{1} & \colhead{2}
}
\startdata
a & b \\
c & d % !!!! crash if no "\\" placed here
\enddata
\end{deluxetable}

\end{document}
```

Results in:

```
./demo.tex:16: Misplaced \omit.
\startdata ... {\vskip -9pt}\pt@head \par #1\omit 
                                                  \\\omit \\\hline \end {tab...
l.16 \enddata

./demo.tex:16:  ==> Fatal error occurred, no output PDF file produced!
```

Seen with `aastex6` version 6.0 (March 2, 2016).

**Comment by gregschwarz** [comment] 2016-04-05 17:08
Version 6 of AASTeX is based on emulateapj. The missing \\\\ at the end of the last line was actually a bug in emulateapj which has now been fixed. The problem is that many people are used to leaving it off so it will take some time to get used to the correct practice of ending all deluxetable data lines with \\\\.

**Comment by pkgw** [comment] 2016-04-09 16:02
Standard LaTeX tables are intended to be written without the final `\\`, so it would be good to not crash in the case that it is missing.

**Comment by gregschwarz** [comment] 2016-04-11 11:38
I wouldn't say standard LaTeX is intended to be written without the final \\. It may be allowed but it is not standard practice to leave it off. I will ask our latex programmer what she can do about cases where this is left out. If something can be done we will add to the next release.

**Comment by pkgw** [comment] 2016-04-12 02:08
Hmmm, I thought that including a final `\\` ended up yielding unwanted extra space below the last row of the table in standard LaTeX, but my experiments are indicating that this is not the case. Still, I think this would be nice to fix if it's not too difficult.

**Comment by gregschwarz** [comment] 2016-04-12 11:54
I have added it to the bug list. We will see what the latex programmer says is possible.

**Comment by augustfly** [comment] 2016-11-29 12:46
I have tested and confirmed that leaving off `\\` from the last row of a deluxetable produces the following **error state in released v6.1**. The test case is that posted by @pkgw above. The presence of `\floattable` does not appear relevant to the error state. 

> ! Misplaced \omit.
\startdata ... {\vskip -9pt}\pt@head \par #1\omit 
                                                  \\\omit \\\hline \end {tab...
l.20 \enddata

Note: adding `\\` to the last row of the table **does not produce** any additional spacing between the last row and the last horizontal rule. 

I can't tell what is acceptable or not wrt to closing this issue @pkgw @gregschwarz

**Comment by gregschwarz** [comment] 2016-11-29 13:07
I thought that the leaving off the trailing "\\" was fixed in this version but you are right. If you tell the compiler to do what it can to fix it with the "r" option it does produce the right tabular result but this is hardly ideal.

**Comment by elisabethadams** [comment] 2016-12-16 01:17
Just wanted to comment to say that I ran into this issue after upgrading to v6.1 (at the journal's request!), so +1 to fixing it. The error message (which is unfortunately a very common LaTeX error) took a while to lead me here.

**Comment by augustfly** [comment] 2017-07-31 20:24
@gregschwarz is this queued for v6.2? can it be?

**Closed** 2018-02-23 20:21 UTC
Labels: bug, tables
